# Generated by Django 2.0.3 on 2018-03-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20180311_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='ros_msg_type',
            field=models.CharField(choices=[('DVL', 'DvlData'), ('IMU', 'IMUDATA')], max_length=15),
        ),
    ]
