# Generated by Django 3.0.dev20190404063328 on 2019-04-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('people', models.ManyToManyField(to='test_app.TestModel')),
            ],
        ),
    ]
